"""Pydantic schemas for request/response validation."""

from app.schemas.auth import (
    LoginRequest,
    LogoutRequest,
    LogoutResponse,
    RefreshTokenRequest,
    TokenRefreshResponse,
    TokenResponse,
)
from app.schemas.common import (
    ApiResponse,
    ErrorDetail,
    ErrorResponse,
    ErrorResponseWithCode,
    ValidationErrorResponse,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectInDB,
    ProjectListResponse,
    ProjectMemberCreate,
    ProjectMemberListResponse,
    ProjectMemberResponse,
    ProjectResponse,
    ProjectUpdate,
)
from app.schemas.stats import (
    ActivityHourData,
    ActivityTrendResponse,
    AIAdoptionResponse,
    BugTrendResponse,
    CodeRankResponse,
    CodeTrendResponse,
    PersonalBugRateResponse,
    PersonalCodeStatsResponse,
    PersonalDashboardResponse,
    PersonalTokenStatsResponse,
    ProjectDashboardResponse,
    ProjectStatsResponse,
    TokenTrendResponse,
    TopUserResponse,
)
from app.schemas.sync import (
    SyncGitLabRequest,
    SyncLogListResponse,
    SyncLogResponse,
    SyncStatusData,
    SyncTaskCreate,
    SyncTaskCreateData,
    SyncTaskCreateResponse,
    SyncTaskDetailData,
    SyncTaskDetailResponse,
    SyncTaskInDB,
    SyncTaskListData,
    SyncTaskListResponse,
    SyncTaskResponse,
    SyncTraeRequest,
    SyncZendaoRequest,
)
from app.schemas.user import (
    ChangePasswordRequest,
    RoleResponse,
    UserCreate,
    UserInDB,
    UserListResponse,
    UserProfileUpdate,
    UserResponse,
    UserUpdate,
)

__all__ = [
    # Common
    "ApiResponse",
    "ErrorResponse",
    "ErrorDetail",
    "ValidationErrorResponse",
    "ErrorResponseWithCode",
    # Auth
    "LoginRequest",
    "TokenResponse",
    "TokenRefreshResponse",
    "RefreshTokenRequest",
    "LogoutRequest",
    "LogoutResponse",
    # User
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "UserListResponse",
    "RoleResponse",
    "UserProfileUpdate",
    "ChangePasswordRequest",
    # Project
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectInDB",
    "ProjectListResponse",
    "ProjectMemberCreate",
    "ProjectMemberResponse",
    "ProjectMemberListResponse",
    # Stats
    "TokenTrendResponse",
    "ActivityTrendResponse",
    "ActivityHourData",
    "TopUserResponse",
    "ProjectStatsResponse",
    "CodeRankResponse",
    "BugTrendResponse",
    "AIAdoptionResponse",
    "PersonalCodeStatsResponse",
    "PersonalTokenStatsResponse",
    "PersonalBugRateResponse",
    "PersonalDashboardResponse",
    "ProjectDashboardResponse",
    "CodeTrendResponse",
    # Sync
    "SyncGitLabRequest",
    "SyncTraeRequest",
    "SyncZendaoRequest",
    "SyncTaskCreate",
    "SyncTaskCreateResponse",
    "SyncTaskResponse",
    "SyncTaskDetailResponse",
    "SyncTaskInDB",
    "SyncTaskListResponse",
    "SyncLogResponse",
    "SyncLogListResponse",
    # Sync Data schemas
    "SyncTaskCreateData",
    "SyncTaskDetailData",
    "SyncTaskListData",
    "SyncStatusData",
]
